#ifndef _MOSQUITTO_CLIENT_H
#define _MOSQUITTO_CLIENT_H

typedef enum _ARG_SUB
{
	ARG_SUB_MIN,
	ARG_SUB_HOST,
	ARG_SUB_HOST_VALUE,
	ARG_SUB_PORT,
	ARG_SUB_PORT_VALUE,
	ARG_SUB_CAFILE,
	ARG_SUB_CAFILE_VALUE,
	ARG_SUB_CERT,
	ARG_SUB_CERT_VALUE,
	ARG_SUB_KEY,
	ARG_SUB_KEY_VALUE,
	ARG_SUB_USER_NAME,
	ARG_SUB_USER_NAME_VALUE,
	ARG_SUB_USER_PASSWD,
	ARG_SUB_USER_PASSWD_VALUE,
	ARG_SUB_CLIENT_ID,
	ARG_SUB_CLIENT_ID_VALUE,
	ARG_SUB_TOPIC01,
	ARG_SUB_TOPIC01_VALUE,
	ARG_SUB_MAX,
}ARG_SUB;

typedef enum _ARG_PUB
{
	ARG_PUB_MIN,
	ARG_PUB_HOST,
	ARG_PUB_HOST_VALUE,
	ARG_PUB_PORT,
	ARG_PUB_PORT_VALUE,
	ARG_PUB_CAFILE,
	ARG_PUB_CAFILE_VALUE,
	ARG_PUB_CERT,
	ARG_PUB_CERT_VALUE,
	ARG_PUB_KEY,
	ARG_PUB_KEY_VALUE,
	ARG_PUB_USER_NAME,
	ARG_PUB_USER_NAME_VALUE,
	ARG_PUB_USER_PASSWD,
	ARG_PUB_USER_PASSWD_VALUE,
	ARG_PUB_CLIENT_ID,
	ARG_PUB_CLIENT_ID_VALUE,
	ARG_PUB_MSG,
	ARG_PUB_MSG_VALUE,
	ARG_PUB_TOPIC01,
	ARG_PUB_TOPIC01_VALUE,
	ARG_PUB_MAX,
}ARG_PUB;

extern int main_mosquitto_sub(int argc, char *argv[]);
extern int main_mosquitto_pub(int argc, char *argv[]);


#endif	// _MOSQUITTO_CLIENT_H
